[package]
name = "generated_client"
version = "0.1.0"
authors = ["Gérald Lelong <gerald.lelong@easymov.fr>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
surf = "1.0.3"
async-std = "1.1.0"
femme = "1.3.0"
log = "0.4.8"
serde = { version = "1.0.102", features = ["derive"] }
